name: Publish Docker image
on:
  push:
    branches: [ master ]
jobs:
  
  push_to_registries:
    name: Build and push containers
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push image
        uses: docker/login-action@v1 
        with:
          # dockerhub registry used
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }} 
      - run: | 
          docker build . -t grinchub/e-filing-test:nginx-fpm-docker
          docker push grinchub/e-filing-test:nginx-fpm-docker